kddnewton/yarv

.github/workflows/spec.yml, .gitmodules
Closes #15 
This PR sets up `mspec` and `spec/ruby` to run against `exe/yarv`. Obviously it fails.
I have not added an `|| true` guard, because I feel that having the spec task look like it passes might encourage us to overlook it. However I'm willing to be persuaded otherwise given how demotivating it is to always see PR's with a ❌
=> Configure Ruby Spec to run on GH Actions

lib/yarv.rb, lib/yarv/opt_str_uminus.rb, test/yarv_test.rb
=> Implement opt_str_uminus

lib/yarv.rb, lib/yarv/opt_minus.rb, test/yarv_test.rb
=> Adding the opt_minus instruction

lib/yarv.rb, lib/yarv/dup.rb, lib/yarv/setglobal.rb, test/setglobal_test.rb
=> Set global variables

lib/yarv/opt_minus.rb, lib/yarv/opt_str_uminus.rb
Our previous change, https://github.com/kddnewton/yarv/pull/30, caused some new instruction files to be broken. We've fixed the tests.
=> Update API for instruction's execution method to use execution context

lib/yarv.rb, lib/yarv/opt_and.rb, test/opt_and_test.rb
=> Implement opt_and

lib/yarv.rb, lib/yarv/pop.rb
=> Implement pop

lib/yarv.rb, lib/yarv/opt_div.rb, test/opt_div_test.rb
Also swap the order a bit to keep them alphabetical
Fixes #53
=> Implement opt_div

lib/yarv.rb, lib/yarv/opt_nil_p.rb, test/opt_nil_p_test.rb
=> Implement opt_nil_p

lib/yarv.rb, lib/yarv/putobject_int2fix_0.rb, test/putobject_int2fix_0_test.rb
Closes: https://github.com/kddnewton/yarv/issues/65
=> Implement `putobject_INT2FIX_0_`

lib/yarv.rb, lib/yarv/opt_length.rb, test/opt_length_test.rb
=> Implement opt_length

lib/yarv.rb, lib/yarv/opt_succ.rb, test/opt_succ_test.rb
=> Implement opt_succ

README.md
Point out the test_insns.rb bootstrap tests that exist in CRuby to help with generating specific instructions.
=> Add a note to the README about test_insns.rb

lib/yarv.rb, lib/yarv/getlocal_wc_0.rb, lib/yarv/setlocal_wc_0.rb, test/getlocal_wc_0_test.rb, test/setlocal_wc_0_test.rb
=> Get and set local variables on the current frame

lib/yarv.rb, lib/yarv/putnil.rb, test/branchunless_test.rb, test/putnil_test.rb
Closes https://github.com/kddnewton/yarv/issues/25
=> Add PutNil

lib/yarv.rb, lib/yarv/newarray.rb, test/newarray_test.rb
=> Implement newarray

lib/yarv.rb, lib/yarv/opt_mod.rb, test/opt_mod_test.rb
=> Implement opt_mod

lib/yarv.rb, lib/yarv/swap.rb, test/swap_test.rb
Needs to be rebased after https://github.com/kddnewton/yarv/pull/96 and https://github.com/kddnewton/yarv/pull/85
=> Implement `swap`

lib/yarv.rb, lib/yarv/dup_hash.rb, test/dup_hash_test.rb
=> Implement duphash instruction

lib/yarv.rb, lib/yarv/jump.rb, test/jump_test.rb
Closes: https://github.com/kddnewton/yarv/issues/64
Jump determines the jump index based on the relevant label from the instruction sequence, and moves the program counter accordingly.
=> Implement `jump` instruction

lib/yarv/concatarray.rb, lib/yarv/duparray.rb, lib/yarv/newarray.rb, lib/yarv/newhash.rb
I forgot to define pretty_print in #91 #94 #100 #106
=> Add pretty_print for instructions

lib/yarv.rb, lib/yarv/opt_ge.rb, lib/yarv/opt_gt.rb, lib/yarv/opt_le.rb, lib/yarv/opt_lt.rb, test/opt_ge_test.rb, test/opt_gt_test.rb, test/opt_le_test.rb, test/opt_lt_test.rb
=> Implement `opt_le`, `opt_lt`, `opt_ge`, `opt_gt`

lib/yarv.rb, lib/yarv/opt_aref_with.rb, test/opt_aref_with_test.rb
=> Implement opt_aref_with instruction

.github/workflows/spec.yml
This was supposed to be included in 7672306...
=> Fix workflow on for spec

lib/yarv.rb, lib/yarv/opt_size.rb, test/opt_size_test.rb
=> Implement opt_size

lib/yarv.rb, lib/yarv/opt_mult.rb, test/opt_mult_test.rb
Resolves https://github.com/kddnewton/yarv/issues/132
=> Add opt_mult

lib/yarv.rb, lib/yarv/opt_neq.rb, test/opt_neq_test.rb
=> Implement opt_neq

lib/yarv.rb
Before this change, calls to require were going to the host ruby
Kernel#require, which meant that we weren't actually running any of the
code ourselves.
=> Implement basic require method

lib/yarv.rb, lib/yarv/newrange.rb, test/newrange_test.rb
=> Implement newrange

lib/yarv.rb, lib/yarv/opt_aset.rb, lib/yarv/setn.rb, test/opt_aset_test.rb
=> Implement opt_aset

lib/yarv.rb, lib/yarv/opt_ltlt.rb, test/opt_ltlt_test.rb
=> Implement opt_ltlt

lib/yarv.rb, lib/yarv/toregexp.rb, test/toregexp_test.rb
=> Implement toregexp

lib/yarv/execution_context.rb, lib/yarv/frame.rb, lib/yarv/insn/invokeblock.rb, lib/yarv/instruction_sequence.rb, test/insn/invokeblock_test.rb
=> Add Invokeblock instruction

exe/yarv, lib/yarv.rb, lib/yarv/cfg.rb, lib/yarv/insn/branchif.rb, lib/yarv/insn/branchnil.rb, lib/yarv/insn/branchunless.rb, lib/yarv/insn/insn.rb, lib/yarv/insn/jump.rb, lib/yarv/insn/leave.rb, lib/yarv/instruction_sequence.rb, test/cfg_test.rb
```ruby
n = 10
sum = 0
while n > 0
sum += n
n -= 1
end
sum
```
```
% bundle exec exe/yarv --dump=cfg test.rb
== cfg #<ISeq:<compiled>>
block_0:
0000 putobject                              10
0001 setlocal_WC_0                          n@0
0002 putobject_INT2FIX_0_
0003 setlocal_WC_0                          sum@1
0004 jump                                   label_28 (16)
0005 putnil
0006 pop
0007 jump                                   label_28 (16)
block_8: # from: block_16
0008 getlocal_WC_0                          sum@1
0009 getlocal_WC_0                          n@0
0010 opt_plus                               <calldata!mid:+, argc:1, ARGS_SIMPLE>[CcCr]
0011 setlocal_WC_0                          sum@1
0012 getlocal_WC_0                          n@0
0013 putobject_INT2FIX_1_
0014 …
```
=> Implement a basic CFG

lib/yarv.rb
Hi! I fixed a typo in `lib/yarv.rb` :)
=> Fix typo in lib/yarv.rb

exe/yarv, lib/yarv/main.rb
=> Fix some blockers to actually running ruby/spec
